# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XM_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('userpass', models.CharField(max_length=30, verbose_name='密码')),
                ('useremail', models.EmailField(max_length=30, verbose_name='邮箱')),
                ('usertype', models.CharField(max_length=30, verbose_name='用户类型')),
            ],
        ),
    ]
