# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='XM_User',
            new_name='User',
        ),
    ]
